{% set name = "apache-airflow-providers-amazon" %}
{% set version = "8.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-amazon-{{ version }}.tar.gz
  sha256: 684d9c4c920ca1ecda76cfd97cbb6c9beeb8c94534a595ac674a5e9ad3db4e30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow-providers-http
    - apache-airflow >=2.4.0
    - asgiref
    - boto3 >=1.28.0
    - botocore >=1.31.0
    - jsonpath-ng >=1.5.3
    - redshift_connector >=2.0.888
    - sqlalchemy-redshift >=0.8.6
    - watchtower >=2.0.1,<2.1.dev0
    # temporary constrain because of dependency fails in https://github.com/conda-forge/connexion-feedstock/pull/34
    - werkzeug >=1.0,<2.3
    - flask >=1.0.4,<2.3

test:
  imports:
    - airflow.providers.amazon
    - airflow.providers.amazon.aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-amazon package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
