{% set name = "apache-airflow-providers-amazon" %}
{% set version = "8.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_amazon-{{ version }}.tar.gz
  sha256: f248e51ec86f58e3435095b1f8a85991e685f16748c1f4100dc62c9611a5754b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow-providers-http
    - apache-airflow >=2.5.0
    - asgiref
    - boto3 >=1.28.0
    - botocore >=1.31.0
    - inflection >=0.5.1
    - jsonpath-ng >=1.5.3
    - redshift_connector >=2.0.888
    - sqlalchemy-redshift >=0.8.6
    - watchtower >=2.0.1,<4

test:
  imports:
    - apache_airflow_providers_amazon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-amazon for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/amazon/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
