{% set name = "apache-airflow-providers-amazon" %}
{% set version = "7.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-amazon-{{ version }}.tar.gz
  sha256: 33724df42ab419c02352041aedbcefe682d7f8a314b7227ca75c9774fc9f37a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.2.0
    - pip
  run:
    - python >=3.7
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.3.0
    - boto3 >=1.24.0
    - jsonpath-ng >=1.5.3
    - mypy-boto3-appflow >=1.24.0
    - mypy_boto3_rds >=1.24.0
    - mypy-boto3-redshift-data >=1.24.0
    - redshift_connector >=2.0.888
    - sqlalchemy-redshift >=0.8.6
    - watchtower >=2.0.1,<2.1.dev0

test:
  imports:
    - airflow.providers.amazon
    - airflow.providers.amazon.aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-amazon package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
