{% set name = "apache-airflow-providers-amazon" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-amazon-{{ version }}.tar.gz
  sha256: 369d94d47636560fd622e8fab15e934fcbf27a1d52e9645693bf27a21fb94c15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - boto3 >=1.15.0
    - jsonpath-ng >=1.5.3
    - mypy-boto3-redshift-data >=1.21.0
    - mypy_boto3_rds >=1.21.0
    - pandas >=0.17.1
    - redshift_connector >=2.0.888
    - sqlalchemy-redshift >=0.8.6
    - watchtower >=2.0.1,==2.0.*
    - xmltodict <0.13.0

test:
  imports:
    - airflow.providers.amazon
    - airflow.providers.amazon.aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-amazon package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
