{% set name = "apache-airflow-providers-amazon" %}
{% set version = "8.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-amazon-{{ version }}.tar.gz
  sha256: d35e3bba2cf902aff36d99891666dfb4699f9de37a6457fafd02ca308df458ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow-providers-http
    - apache-airflow >=2.5.0
    - asgiref
    - boto3 >=1.28.0
    - botocore >=1.31.0
    - jsonpath-ng >=1.5.3
    - redshift_connector >=2.0.888
    - sqlalchemy-redshift >=0.8.6
    - watchtower >=3.0.1,<3.1.dev0

test:
  imports:
    - airflow.providers.amazon
    - airflow.providers.amazon.aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-amazon package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
