{% set name = "apache-airflow-providers-amazon" %}
{% set version = "8.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_amazon-{{ version }}.tar.gz
  sha256: b86b99da896bbaa3e7f9844c7620214ca46fa9e35f962e9d516c563e775692f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow-providers-common-compat >=1.1.0
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow-providers-http
    - apache-airflow >=2.8.0
    - asgiref >=2.3.0
    - boto3 >=1.34.90
    - botocore >=1.34.90
    - inflection >=0.5.1
    - jmespath >=0.7.0
    - jsonpath-ng >=1.5.3
    - pyathena >=3.0.10
    - redshift_connector >=2.0.918
    - sqlalchemy-redshift >=0.8.6
    - watchtower >=3.0.0,<4

test:
  imports:
    - airflow.providers.amazon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-amazon for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/amazon/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
