{% set name = "apache-airflow-providers-amazon" %}
{% set version = "8.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_amazon-{{ version }}.tar.gz
  sha256: ec09061232961ac1b25641389701268c88c8aebb041dbe67678a8181870e553b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow-providers-http
    - apache-airflow >=2.6.0
    - asgiref
    - boto3 >=1.33.0
    - botocore >=1.33.0
    - inflection >=0.5.1
    - jsonpath-ng >=1.5.3
    - pyathena >=3.0.10
    - redshift_connector >=2.0.918
    - sqlalchemy-redshift >=0.8.6
    - watchtower >=2.0.1,<4

test:
  imports:
    - airflow.providers.amazon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-amazon for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/amazon/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
